<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\Sandbox\Impeller.targets" />

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
    <RootNamespace>HelloWPFImpellerGallery</RootNamespace>
    <AssemblyName>HelloWPFImpellerGallery</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NImpeller\NImpeller.csproj" />
    <ProjectReference Include="..\..\src\NImpeller.Wpf\NImpeller.Wpf.csproj" />
  </ItemGroup>

</Project>
